### ISSUE TITLE
where is the train.py

### ISSUE THREAD

**Issue by JWSunny** [Seymour-Lee/face-detection-ssd-mobilenet#1]
hello:
when i train the model, i cant't find the train.py, can you tell me which train.py that you choose in the object_detection?
thanks, best wish

**Comment by Seymour-Lee** [comment]
Oh sorry, I have not noticed your issue.

The train.py is in this project: https://github.com/tensorflow/models. You can find the training scripts in models/research/object_detection.

I use tensorflow object detection API to train and eval the model automaticly. After reading the documents in that repo, you will know how to do that.

Bests
